name: training_pipeline

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "training pipeline triggered. Add real steps later."
